### ISSUE TITLE
Clicking "focus on Node" for an Exposure removes all nodes, irrespective of association to given Exposure

### ISSUE THREAD

**Issue by swanderz** [fishtown-analytics/dbt-docs#176]
### Describe the bug
You can't "select" exposures to focus on in the docs DAG view

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

1. bring up DAG for a project
    
    <img width="1504" alt="image" src="https://user-images.githubusercontent.com/8158673/107573258-23893280-6ba2-11eb-93e0-c19219d11edf.png">
2. Either:
    1. Click "Refocus on Node" from the Exposure's right click context menu, or
    2. Type: `+exposure:ALLI Survey Analysis` into the `--select` flag box
    
    <img width="389" alt="image" src="https://user-images.githubusercontent.com/8158673/107573618-9e524d80-6ba2-11eb-81ae-ebb82e8c652f.png">
    <img width="206" alt="image" src="https://user-images.githubusercontent.com/8158673/107573717-c04bd000-6ba2-11eb-921a-96757c9c6fb7.png">
3. All nodes disappear
    <img width="1149" alt="image" src="https://user-images.githubusercontent.com/8158673/107573825-dfe2f880-6ba2-11eb-80ea-436ad3be40c0.png">

### Expected behavior
In the above example, actually the DAG would stay exactly the same, as if I had selected the `channel_percent` model and all upstreams (i.e. `+channel_percent+`, which is a decent workaround for this scenario)

**The output of `dbt --version`:**
```
installed version: 0.19.0
   latest version: 0.19.0

Up to date!

Plugins:
  - sqlserver: 0.19.0
```

### Additional context
n/a

**Comment by jtcohen6** [comment]
Thanks for the detailed bug report @swanderz! The issue here is that your exposure name has spaces in it. Rather than rework dbt-docs to support node names with spaces, I think the real resolution is for dbt to raise an error if it finds a node name with spaces.

https://github.com/fishtown-analytics/dbt-docs/issues/168
https://github.com/fishtown-analytics/dbt/issues/2970

Does that sound reasonable to you? Do you have a strong preference for being able to use spaces in exposure names?

**Comment by swanderz** [comment]
> Does that sound reasonable to you?

yep totally makes sense -- thanks!
